export const INCREASE_COUNT = 'INCREASE_COUNT';
export const DECREASE_COUNT = 'DECREASE_COUNT';

// ATM
export const ATM_WITHDRAW = 'ATM_WITHDRAW';
export const ATM_DEPOSIT = 'ATM_DEPOSIT';
// PHOTO
export const GALLERY_GET_PHOTOS = 'GALLERY_GET_PHOTOS';
export const GALLERY_GET_PHOTOS_PENDING = 'GALLERY_GET_PHOTOS_PENDING';
export const GALLERY_GET_PHOTOS_SUCCESS = 'GALLERY_GET_PHOTOS_SUCCESS';
export const GALLERY_GET_PHOTOS_ERROR = 'GALLERY_GET_PHOTOS_ERROR';
