// ------------------------------------------------
// ASYNC ACTION: SHOP_GET_CATEGORIES
export const SHOP_GET_CATEGORIES = 'SHOP_GET_CATEGORIES';
export const SHOP_GET_CATEGORIES_PENDING = 'SHOP_GET_CATEGORIES_PENDING';
export const SHOP_GET_CATEGORIES_SUCCESS = 'SHOP_GET_CATEGORIES_SUCCESS';
export const SHOP_GET_CATEGORIES_ERROR = 'SHOP_GET_CATEGORIES_ERROR';
// ------------------------------------------------
// ASYNC ACTION: SHOP_GET_PRODUCTS_BY_CATEGORY
export const SHOP_GET_PRODUCTS_BY_CATEGORY = 'SHOP_GET_PRODUCTS_BY_CATEGORY';
export const SHOP_GET_PRODUCTS_BY_CATEGORY_PENDING = 'SHOP_GET_PRODUCTS_BY_CATEGORY_PENDING';
export const SHOP_GET_PRODUCTS_BY_CATEGORY_SUCCESS = 'SHOP_GET_PRODUCTS_BY_CATEGORY_SUCCESS';
export const SHOP_GET_PRODUCTS_BY_CATEGORY_ERROR = 'SHOP_GET_PRODUCTS_BY_CATEGORY_ERROR';
// ------------------------------------------------
// ASYNC ACTION: SHOP_GET_PRODUCT_BY_ID
export const SHOP_GET_PRODUCT_BY_ID = 'SHOP_GET_PRODUCT_BY_ID';
export const SHOP_GET_PRODUCT_BY_ID_PENDING = 'SHOP_GET_PRODUCT_BY_ID_PENDING';
export const SHOP_GET_PRODUCT_BY_ID_SUCCESS = 'SHOP_GET_PRODUCT_BY_ID_SUCCESS';
export const SHOP_GET_PRODUCT_BY_ID_ERROR = 'SHOP_GET_PRODUCT_BY_ID_ERROR';

// SHOPPING CART
export const SHOP_ADD_PRODUCT_TO_CART = 'SHOP_ADD_PRODUCT_TO_CART';
export const SHOP_REMOVE_PRODUCT_FROM_CART = 'SHOP_REMOVE_PRODUCT_FROM_CART';
export const SHOP_CLEAR_CART = 'SHOP_CLEAR_CART';

// CHECK OUT
export const SHOP_CHECKOUT = 'SHOP_CHECKOUT';
export const SHOP_CHECKOUT_PENDING = 'SHOP_CHECKOUT_PENDING';
export const SHOP_CHECKOUT_SUCCESS = 'SHOP_CHECKOUT_SUCCESS';
export const SHOP_CHECKOUT_ERROR = 'SHOP_CHECKOUT_ERROR';
