export const INCREASE_COUNT = 'INCREASE_COUNT';
export const DECREASE_COUNT = 'DECREASE_COUNT';

// ATM
export const ATM_WITH_DRAW = 'ATM_WITH_DRAW';
export const ATM_DEPOSITE = 'ATM_DEPOSITE';
// PHOTO

export const GET_PHOTOS_PENDING = 'GET_PHOTOS_PENDING';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const GET_PHOTOS_ERROR = 'GET_PHOTOS_ERROR';
