export const MAIN_ADD_TO_CART = 'MAIN_ADD_TO_CART';
export const MAIN_REMOVE_FROM_CART = 'MAIN_REMOVE_FROM_CART';

export const MAIN_INCREASE_CART = 'MAIN_INCREASE_CART';
export const MAIN_DECREASE_CART = 'MAIN_DECREASE_CART';

export const MAIN_CLEAR_CART = 'MAIN_CLEAR_CART';
