// COUNTER
export const SHOPPING_ADD_TO_CART = 'SHOPPING_CART_ADD_TO_CART';
export const SHOPPING_DECREASE_FROM_CART = 'SHOPPING_DECREASE_FROM_CART';
export const SHOPPING_REMOVE_FROM_CART = 'SHOPPING_REMOVE_FROM_CART';
export const SHOPPING_EMPTY_CART = 'SHOPPING_EMPTY_CART';
