export const AUTH_LOGIN_STACK_NAVIGATOR = 'AUTH_LOGIN_STACK';
export const AUTH_LOGIN_SCREEN = 'LOGIN_SCREEN';
export const AUTH_REGISTER_SCREEN = 'AUTH_REGISTER_SCREEN';

export const MAIN_TAB_NAVIGATOR = 'MAIN_TAB_NAVIGATOR';
