export const AUTH_SIGNIN_STACK_NAVIGATOR = 'AUTH_SIGNIN_STACK';
export const AUTH_SIGNIN_SCREEN = 'SIGNIN_SCREEN';
export const AUTH_REGISTER_SCREEN = 'AUTH_REGISTER_SCREEN';

export const USER_TAB_NAVIGATOR = 'USER_TAB_NAVIGATOR';
export const WORKER_TAB_NAVIGATOR = 'WORKER_TAB_NAVIGATOR';
