// ------------------------------------------------
// ASYNC ACTION: SHOP_GET_CATEGORIES
export const SHOP_GET_CATEGORIES = 'SHOP_GET_CATEGORIES';
export const SHOP_GET_CATEGORIES_PENDING = 'SHOP_GET_CATEGORIES_PENDING';
export const SHOP_GET_CATEGORIES_SUCCESS = 'SHOP_GET_CATEGORIES_SUCCESS';
export const SHOP_GET_CATEGORIES_ERROR = 'SHOP_GET_CATEGORIES_ERROR';
// ------------------------------------------------
// ASYNC ACTION: SHOP_GET_PRODUCTS_BY_CATEGORY
export const SHOP_GET_PRODUCTS_BY_CATEGORY = 'SHOP_GET_PRODUCTS_BY_CATEGORY';
export const SHOP_GET_PRODUCTS_BY_CATEGORY_PENDING = 'SHOP_GET_PRODUCTS_BY_CATEGORY_PENDING';
export const SHOP_GET_PRODUCTS_BY_CATEGORY_SUCCESS = 'SHOP_GET_PRODUCTS_BY_CATEGORY_SUCCESS';
export const SHOP_GET_PRODUCTS_BY_CATEGORY_ERROR = 'SHOP_GET_PRODUCTS_BY_CATEGORY_ERROR';
// ------------------------------------------------
// ASYNC ACTION: SHOP_GET_PRODUCT_BY_ID
export const SHOP_GET_PRODUCT_BY_ID = 'SHOP_GET_PRODUCT_BY_ID';
export const SHOP_GET_PRODUCT_BY_ID_PENDING = 'SHOP_GET_PRODUCT_BY_ID_PENDING';
export const SHOP_GET_PRODUCT_BY_ID_SUCCESS = 'SHOP_GET_PRODUCT_BY_ID_SUCCESS';
export const SHOP_GET_PRODUCT_BY_ID_ERROR = 'SHOP_GET_PRODUCT_BY_ID_ERROR';
