// PRODUCT
export const GET_PRODUCTS = 'GET_PRODUCTS';

// SHOPPING CART
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SHOW_SHOPPING_CART = 'SHOW_SHOPPING_CART';
export const HIDE_SHOPPING_CART = 'HIDE_SHOPPING_CART';