# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeOnlineShop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeOnlineShop
  pod 'Firebase/Messaging'
 
  target 'ReactNativeOnlineShopTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'ReactNativeOnlineShop-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeOnlineShop-tvOS

  target 'ReactNativeOnlineShop-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
