// COUNTER
export const INCREASE_COUNT = 'INCREASE_COUNT';
export const DECREASE_COUNT = 'DECREASE_COUNT';

// ASYNC API
// PHOTO
export const GET_PHOTOS = 'GET_PHOTOS';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const GET_PHOTOS_ERROR = 'GET_PHOTOS_ERROR';
export const GET_PHOTOS_PENDING = 'GET_PHOTOS_PENDING';

// ALBUM
export const GET_ALBUMS = 'GET_ALBUMS';
export const ADD_ALBUM = 'ADD_ALBUM';

// AUTH
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';

// THEME
export const UPDATE_THEME = 'UPDATE_THEME';

// SHOPPING CART
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SHOW_SHOPPING_CART = 'SHOW_SHOPPING_CART';
export const HIDE_SHOPPING_CART = 'HIDE_SHOPPING_CART';